### PR TITLE
Update StrEnum to be case insensitive

### PR DESCRIPTION
**Pull request by DarkKronicle**
Spotify recently changed their enums to be all caps in some cases. I found them specifically in `album_type` it's `ALBUM` instead of `album`, which breaks tekore in some cases. tekore broke because it assumed that these keys were a specific case. 

The change I've implemented makes it so that when creating the tekore models, finding the AlbumType and other StrEnum objects is case insensitive. This will help future proof in case Spotify does something similar again in the future. My implementation does not modify values of the enums, just how they are stored and later indexed. If a different solution is desired, let me know.

- [x] Tests written with 100% coverage
- [x] Documentation and changelog entry written
- [x] All `tox` checks passed with an appropriately configured
  [environment](https://github.com/felix-hilden/tekore#running-tests)

### CODE REVIEW

**Comment by felix-hilden** [comment]
Thanks for submitting! Seems reasonable, I'd like to see some tests if you're up for it!

**Comment by felix-hilden** [comment]
Just a few tests verifying that the new meta works 👌

**Comment by felix-hilden** [comment]
Hi! I'm fixing another issue as well and it would be good to release these at the same time. Are you down to write the tests in the near future? If not, I could just push some on this branch and we'll get it in.

**Comment by felix-hilden** [comment]
Other tests should pretty much pass now if you rebase on master!

**Comment by DarkKronicle** [comment]
Wrote some tests. Realized I had accidentally set the value to lowercase in the lookup and not the key, which would have done nothing. That's fixed now.

**Comment by felix-hilden** [comment]
Thanks for testing it too! Apparently I wasn't in such a hurry :P Sorry for taking so long. It'll be released today!

**Pull request merged**
