### PR TITLE
update license to GPLV3

### PR DESCRIPTION
**Pull request by libererer**

### CODE REVIEW

**Comment by libererer** [comment]
🥺

**Comment by felix-hilden** [comment]
Sorry, I'm not interested in relicensing the whole repo. But if you want these to land better, I suggest providing at least some reason why you are suggesting the change!

**Comment by libererer** [comment]
GPLV3 have the four essential freedoms: [[1]](https://www.gnu.org/philosophy/free-sw.en.html#f1)

> 1. The freedom to run the program as you wish, for any purpose (freedom 0).
> 2. The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
> 3. The freedom to redistribute copies so you can help others (freedom 2).
> 4. The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

totally different from MIT, APACHE licenses.... .

Forgive my bad things.
Thank you ❤

**Comment by felix-hilden** [comment]
Well, to be fair, MIT is pretty much the epitome of freedom. But thanks for responding anyway!

**Pull request closed without merging**
