### PR TITLE
Added artist follower example

### PR DESCRIPTION
**Pull request by marioortizmanero**
Uploading the script I told you from #148.

* What else can I add to the description?
* Should it use `config_from_credentials`?
* Anything you would like to improve?

### CODE REVIEW

**Comment by felix-hilden** [comment]
Thanks! As I said, nice idea and would make a good addition to the examples. Generally the code looks good, especially `prompt_user`. But I have some ideas, if you'd allow me to nitpick :D

- The description could be split into two lines, e.g. after "following".
- Yes, it should use `config_from_environment` (that's what you meant, right? :D). That way we don't have to guess the callback for example. And it's consistent with other examples.
- After that change the token prompt can be a one-line function if the scope is constructed beforehand
- Use `max_limits` and `all_items` to actually get everything

And a bigger, logical change: we can first fetch all the artists, then check if they are not followed and finally prompt for each one. This achieves three things.
- Checking for membership in the set is not needed
- We can send all artists for the follow check at once, reducing API calls
- Clear flow: get artists - get follow status - prompt for unfollowed

Do you agree? And would you like to make these changes, or should I?

**Comment by marioortizmanero** [comment]
Thanks for the recommendations!

> The description could be split into two lines, e.g. after "following".

Something like:

```
This script will find all the artists you aren't already following. It will check all your playlists, and prompt you to start following them
```

Or what exactly did you mean?

> Yes, it should use config_from_environment (that's what you meant, right? :D). That way we don't have to guess the callback for example. And it's consistent with other examples. 
> After that change the token prompt can be a one-line function if the scope is constructed beforehand

Yup, that's what I meant haha

> Use max_limits and all_items to actually get everything

How does that work? I'll have to read the docs in detail, I didn't know these were a thing.

> And a bigger, logical change: we can first fetch all the artists, then check if they are not followed and finally prompt for each one. This achieves three things.
>    * Checking for membership in the set is not needed
>    * We can send all artists for the follow check at once, reducing API calls
>    * Clear flow: get artists - get follow status - prompt for unfollowed

Yeah that's definitely a better idea. I didn't make the script with the intention to have it shown as an example, so it's just a quick hack haha. With the methods you suggested this does seem like a better alternative.

I'm a bit busy right now, but I think I'll have time this week to polish it. But if you want to do it yourself, or edit anything, go ahead.

**Comment by felix-hilden** [comment]
Just meant splitting the line for line length's sake, but for sure they can be two separate sentences as well. `max_limits` allows to set all paging limits to their maximum values by default, `all_items` retrieves all items of a paging.

I intend to release 1.3 as soon as possible, and it would be nice to have this in the release as well. If you're busy, I'll take a look at this tomorrow.

**Comment by felix-hilden** [comment]
I had an idea while making the changes: a way of chunking list parameters when making requests to avoid length limits. See #153.

I'll squash this in now, thanks for the submission!

**Pull request merged**
